apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-dep-1
  labels:
    env: local
spec:
  selector:
    matchLabels:
      env: local
  template:
    metadata:
      labels:
        app: pod
        env: local
    spec:
      containers:
        -  name: nginx
           image: nginx
  replicas: 4